name: Build and Deploy
defaults:
  run:
    working-directory: webapp

permissions:
  contents: write
on: 
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7
        with:
          repository: OpenBimRL/OpenBimRL-CreatorTool
          path: .
          set-safe-directory: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: pnpm
          cache-dependency-path: webapp/pnpm-lock.yaml

      - name: Install and Build 🔧
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: webapp/dist # The folder the action should deploy.
          repository-name: OpenBimRL/OpenBimRL-CreatorTool
          token: ${{ secrets.GITHUB_TOKEN }}
